#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt  update -y
apt  install nginx -y
apt install ufw
ufw enable
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
systemctl nginx start
